In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [11]:
dataset = pd.read_csv("iris.csv")
dataset.shape
dataset.isnull().sum()
dataset.head()
zero_not_accepted = ['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']
for column in zero_not_accepted:
    dataset[column] = dataset[column].replace(0,np.NaN)
    mean = dataset[column].mean(skipna=True)
    dataset[column] = dataset[column].replace(np.NaN,mean)
    

In [12]:
X = dataset.iloc[:,0:5]
Y = dataset.iloc[:,5]

In [13]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state=0, test_size=0.3)

In [14]:
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.fit_transform(X_test)

In [15]:
#to specify K , we are using sqrt of len of y
import math
math.sqrt(len(Y_train))

10.246950765959598

In [17]:
Classifier = KNeighborsClassifier(n_neighbors=9,p=2,metric="euclidean")
Classifier.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=9, p=2,
                     weights='uniform')

In [21]:
Y_pred = Classifier.predict(X_test)

In [22]:
cm = confusion_matrix(Y_test, Y_pred)

In [23]:
print(cm)

[[16  0  0]
 [ 0 15  3]
 [ 0  0 11]]
