In [3]:
import numpy
array = [1,2,3,4]
print(array)

[1, 2, 3, 4]


In [11]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [18]:
from numpy import *
arr = array([1,2,3,4])
print(arr)

[1 2 3 4]


In [20]:
array = [1,2,3,4]
type(array)

list

In [22]:
arr = array([1,2,3,4],int)
type(arr)


TypeError: 'list' object is not callable

In [25]:
arr = array([10,20,30],int)
type(arr)

TypeError: 'list' object is not callable

In [1]:
quit

In [2]:
arr = array([1,2,3],int)
type(arr)

NameError: name 'array' is not defined

In [6]:
import numpy
arr = array([1,2,3,4],int)
type(arr)

NameError: name 'array' is not defined

In [12]:
import numpy as np
arr = np.array([1,2,3,4])
type(arr)

numpy.ndarray

In [15]:
array = [1,2,3,4]
type(array)

list

In [20]:
a = ([1,2,3,4])
b = array(a)

TypeError: 'list' object is not callable

In [24]:
a = [10,20,30,40]
b = array(a)

TypeError: 'list' object is not callable

In [29]:
a = array(1, 2, 3, 4)
type(a)

TypeError: 'list' object is not callable

In [34]:
a = [1,2,3,4]
b = a
type(b)

list

In [69]:
import numpy
a = array([1,10,2],int)
print(a)
type(a)

[ 1 10  2]


numpy.ndarray

In [79]:
import numpy
a = array([1,10,2],int)
print(a)
type(a) 


a = zeros(5,float)
print(a)


a = ones_like(5,float)
print(a)

[ 1 10  2]
[0. 0. 0. 0. 0.]
1.0


In [143]:
from numpy import *
a =array([1,2,3,4,1,2,2,2,2],int)
sort(a)



array([1, 1, 2, 2, 2, 2, 2, 3, 4])

In [207]:
import numpy
a = [1,12,6,3,12,3,4,5,6]print(sort(a))

[ 1  3  3  4  5  6  6 12 12]


In [1]:

from numpy import *
a = array([4,2,3,1])
sort(a)

quit()


In [17]:

from numpy import *

a = array([1,0,0,2,-4,9,1,1,0])

c = nonzero(a)

print(c)

for i in c:
	print(i)
	
for i in c:
	print(a[i])

	

(array([0, 3, 4, 5, 6, 7]),)
[0 3 4 5 6 7]
[ 1  2 -4  9  1  1]


In [33]:
a = 10
b = 11
id(a)
id(b)

4354893184

In [61]:
a = [1,2,3,4]
b = [1,2,3,4]
print(id(a),id(b))

4413213320 4413211272


In [79]:
a = array([1,2,3,4])
b = [1,2,3,4]
a 
a.view()

array([1, 2, 3, 4])

In [111]:
a = 10
b = 14

id(b)

4354893280

In [113]:
a = 10
b = 14
id(a)
id(b)

4354893280

In [115]:
arr2 = array ([1,2,3,4,5])
arr2.itemsize

8

In [141]:
from numpy import *

arr1 = reshape(arange(10,35),(5,5))
print(arr1)
 
arr1[1:4][1:3]

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]


array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [145]:
a=matrix([[3, 2, 4],
        [2, 5, 3]])
c = sort(a,axis =1)
c

matrix([[2, 3, 4],
        [2, 3, 5]])

In [ ]:
import sys
x = int(input("enter no of rows"))
x
quit()