In [2]:
from numpy import *

arr1 = reshape(arange(10,35),(5,5))
print(arr1)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]


In [4]:
arr1[0:2,1:3]

array([[11, 12],
       [16, 17]])