In [14]:
name = "  srikanth Kante" 
print(name.capitalize())
print(name.rjust(7))
print(name.center(7))
print(name.replace('s','pri'))
print(name.strip())


  srikanth kante
  srikanth Kante
  srikanth Kante
  pririkanth Kante
srikanth Kante


In [31]:
num = [11,2,3,4]
num.insert(5,15)
num.insert(6,20)
num.insert(8,100)
for idasdx in enumerate(num):
    print(idasdx)

(0, 11)
(1, 2)
(2, 3)
(3, 4)
(4, 15)
(5, 20)
(6, 100)


In [37]:
d = {1:'srikanth',2:'sangeetha',3:'babu'}
print(d.get(4,'NA'))
print(d.get(1,'NA'))

NA
srikanth


In [45]:
s = {'1','2','4'}
s.add('1')
print(s)
print(len(s))

{'2', '4', '1'}
3


In [52]:
d = {x:x+1 for x in range(5)}
t=(2,3)
print(d[(2,3)])

KeyError: (2, 3)

In [55]:
class Greeter(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

Hello, Fred
HELLO, FRED!


In [76]:
number = [[1,2,3],[1,2,4]]
import numpy as np
npNumber = np.array(number)
print(npNumber[0,1])
npNumber.shape

2


(2, 3)

In [145]:
a = [1,2,3],[4,5,6],[7,8,9]
b= np.array(a)
print(b)
print("sum \n")
print(b.sum(axis=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
sum 

[ 6 15 24]


In [148]:
a = [[1,2,3],[4,5,6]]
b= np.array(a)
print(b)
print(b.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [176]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a_numpy = np.array(a)
b_numpy = np.empty_like(a_numpy)
v=[1,2,3]
print(a_numpy)
print("\n")
for i in range(3):
    b_numpy[i,:] = a_numpy[i,:] + v
print(b_numpy)    


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [175]:
a_numpy = np.array([[1,2,3],[4,5,6],[7,8,9]])
v = np.array([1,2,3])
vv = np.tile(v,(3,1))
b_numpy= np.empty_like(a_numpy)
b_numpy = a_numpy + vv
print(b_numpy)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [177]:
a_numpy = np.array([[1,2,3],[4,5,6],[7,8,9]])
v = np.array([1,2,3])
b_numpy = a_numpy + v
print(b_numpy)



[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [180]:
from numpy import matrix, rank
A = matrix([[1,3,7],[2,8,3],[7,8,1],[0,0,0]])
print(rank(A))

2


/Users/kants2/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  This is separate from the ipykernel package so we can avoid doing imports until


In [185]:
import numpy
A = numpy.matrix([[1,3,7],[2,8,3],[7,8,1]])
type(A)


numpy.matrixlib.defmatrix.matrix

In [192]:
A = np.array([[1,3,7],[2,8,3],[7,8,1],[0,0,0]])
print(A.shape)
print(A)
print((np.reshape(A,(3,4))).shape)
print(np.reshape(A,(3,4)))

(4, 3)
[[1 3 7]
 [2 8 3]
 [7 8 1]
 [0 0 0]]
(3, 4)
[[1 3 7 2]
 [8 3 7 8]
 [1 0 0 0]]
